services:
  - type: web
    name: medix-frontend
    env: static
    buildCommand: npx update-browserslist-db@latest && npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 